# Generated by Django 4.0.1 on 2022-02-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('poster', models.CharField(max_length=2083)),
                ('genres', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
